FROM golang:1.18.3-bullseye AS build
WORKDIR /build/dfstore
COPY go.mod go.sum ./
RUN go mod tidy
COPY . . 
# build 
RUN go run cmd/main.go 
RUN mkdir -p /build/bin\
    && go build -o /build/bin/dfstore cmd/main.go\
    && go test -c -o /build/bin/dfstore_test ./
RUN apt-get update\
    && apt-get install -y wget gnupg\
    && apt-get install -y net-tools iputils-ping dnsutils

# Production servies 
FROM debian:bullseye AS test
WORKDIR /build
COPY --from=build /build/dfstore ./
COPY --from=build /build/bin ./
ENTRYPOINT  ["/bin/bash"]

# Production servies 
FROM debian:bullseye AS production
WORKDIR /app
COPY --from=build /build/bin/dfstore ./
COPY --from=build /build/bin/dfstore_test ./
COPY --from=build /build/dfstore/testscripts ./
ENTRYPOINT  ["/bin/bash"]
