# This is to set up the testing environment for the unit test
services:
  dfstore_testsetup: 
    build: 
      context: .
      dockerfile: Dockerfile_unittest_env_linux
      target: testsetup 
    image: ${DOCKER_PREFIX}_image_dfstore_testsetup
    container_name: ${DOCKER_PREFIX}_dfstore_testsetup
    depends_on:      
      - redis  
      - postgresql
      - mongo   
    command: testinit.sh 
    stdin_open: true
    tty: true
  redis:
    image: redis
    ports: 
      - "6379:6379"
    container_name: ${DOCKER_PREFIX}_redis
  postgresql:
    image: postgres
    container_name: ${DOCKER_PREFIX}_postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    restart: always
  mongo:
    image: mongo
    container_name: ${DOCKER_PREFIX}_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    restart: always

