# This is supposed to contain the build , test and production related to the project
services:
  dfstore_build: 
    build: 
      context: .
      dockerfile: Dockerfile_build_linux
      target: build 
    image: ${DOCKER_PREFIX}_image_dfstore_build
    container_name: ${DOCKER_PREFIX}_dfstore_build
    depends_on:      
      dfstore_testsetup:
        condition: service_completed_successfully
    stdin_open: true
    tty: true

